# Generated by Django 4.0.6 on 2022-08-05 21:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_app', '0003_city'),
    ]

    operations = [
        migrations.DeleteModel(
            name='City',
        ),
        migrations.DeleteModel(
            name='Personal_info',
        ),
    ]
